/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      300.0,                                       
            catalogName:    "ti.catalog.c6000",
            deviceName:     "TMS320C6748",
            externalMemoryMap: 
           [          
                ["DDR", 
                     {
                        name: "DDR",
                        base: 0xC0000000,                    
                        len: 0x08000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
           ],
          l1DMode:"32k",
          l1PMode:"32k",
          l2Mode:"0k",

    });
    
instance :
    
    override config string codeMemory  = "IRAM";   
    override config string dataMemory  = "IRAM";                                
    override config string stackMemory = "IRAM";
    
}
