#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.C674{1,0,7.3,1
#
keystone_flash.x674: package/cfg/keystone_flash.x674.mak

clean::
	-$(RM) package/cfg/keystone_flash.x674.mak
